version: "3.9"

services:
  mysql:
    image: mysql:8.3                # versión recomendada
    container_name: mysql-users
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: users         # se crea al iniciar
      MYSQL_USER: usr_app
      MYSQL_PASSWORD: usrapp
      MYSQL_ROOT_PASSWORD: rootpwd
      TZ: America/Argentina/Cordoba
    ports:                          # solo para desarrollo
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql   # persistencia
      - ./mysql/initdb/:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "6080:80"
    depends_on:
      - mysql

  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppwd
      TZ: America/Argentina/Cordoba
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/initdb/:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser"]
      interval: 10s
      retries: 5
      start_period: 20s

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - ./pgadmin/config/servers/:/pgadmin4/servers/
      - pgadmin_data:/var/lib/pgadmin

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"   # puerto para aplicaciones
      - "15672:15672" # puerto para la consola web de administración
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

volumes:
  mysql_data:
  postgres_data:
  pgadmin_data:
